# fly.toml app configuration file generated for oh-writers-ws-server-beta on 2026-09-04T12:43:26+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'oh-writers-ws-server-beta'
primary_region = 'fra'

[build]
  dockerfile = 'docker/Dockerfile.ws-server'

[env]
  WS_PORT = '1234'

[http_service]
  internal_port = 1234
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
