/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as RegisterImport } from "./routes/register";
import { Route as LoginImport } from "./routes/login";
import { Route as AppImport } from "./routes/_app";
import { Route as IndexImport } from "./routes/index";
import { Route as InviteTokenImport } from "./routes/invite.$token";
import { Route as DevTokensImport } from "./routes/dev/tokens";
import { Route as AppSettingsImport } from "./routes/_app.settings";
import { Route as AppNotFoundImport } from "./routes/_app.not-found";
import { Route as AppDashboardImport } from "./routes/_app.dashboard";
import { Route as AppCrashTestImport } from "./routes/_app.crash-test";
import { Route as AppTeamsIndexImport } from "./routes/_app.teams.index";
import { Route as AppTeamsNewImport } from "./routes/_app.teams.new";
import { Route as AppTeamsSlugImport } from "./routes/_app.teams.$slug";
import { Route as AppProjectsNewImport } from "./routes/_app.projects.new";
import { Route as AppProjectsIdImport } from "./routes/_app.projects.$id";
import { Route as AppTeamsSlugSettingsImport } from "./routes/_app.teams.$slug_.settings";
import { Route as AppTeamsSlugMembersImport } from "./routes/_app.teams.$slug_.members";
import { Route as AppProjectsIdTreatmentImport } from "./routes/_app.projects.$id_.treatment";
import { Route as AppProjectsIdTitlePageImport } from "./routes/_app.projects.$id_.title-page";
import { Route as AppProjectsIdSynopsisImport } from "./routes/_app.projects.$id_.synopsis";
import { Route as AppProjectsIdSoggettoImport } from "./routes/_app.projects.$id_.soggetto";
import { Route as AppProjectsIdShootingPlanImport } from "./routes/_app.projects.$id_.shooting-plan";
import { Route as AppProjectsIdSettingsImport } from "./routes/_app.projects.$id_.settings";
import { Route as AppProjectsIdSessionsImport } from "./routes/_app.projects.$id_.sessions";
import { Route as AppProjectsIdScreenplayImport } from "./routes/_app.projects.$id_.screenplay";
import { Route as AppProjectsIdScheduleImport } from "./routes/_app.projects.$id_.schedule";
import { Route as AppProjectsIdOutlineImport } from "./routes/_app.projects.$id_.outline";
import { Route as AppProjectsIdOpportunitiesImport } from "./routes/_app.projects.$id_.opportunities";
import { Route as AppProjectsIdLoglineImport } from "./routes/_app.projects.$id_.logline";
import { Route as AppProjectsIdLocationsImport } from "./routes/_app.projects.$id_.locations";
import { Route as AppProjectsIdBudgetImport } from "./routes/_app.projects.$id_.budget";
import { Route as AppProjectsIdBreakdownImport } from "./routes/_app.projects.$id_.breakdown";
import { Route as AppProjectsIdSessionsIndexImport } from "./routes/_app.projects.$id_.sessions.index";
import { Route as AppProjectsIdScreenplayIndexImport } from "./routes/_app.projects.$id_.screenplay.index";
import { Route as AppProjectsIdShootingPlanBlockingEditorImport } from "./routes/_app.projects.$id_.shooting-plan_.blocking-editor";
import { Route as AppProjectsIdSessionsNewImport } from "./routes/_app.projects.$id_.sessions.new";
import { Route as AppProjectsIdSessionsSessionIdImport } from "./routes/_app.projects.$id_.sessions.$sessionId";
import { Route as AppProjectsIdScreenplayVersionsImport } from "./routes/_app.projects.$id_.screenplay.versions";
import { Route as AppProjectsIdScreenplayVersionsVIdImport } from "./routes/_app.projects.$id_.screenplay.versions.$vId";
import { Route as AppProjectsIdScreenplayDiffV1V2Import } from "./routes/_app.projects.$id_.screenplay.diff.$v1.$v2";

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any);

const AppRoute = AppImport.update({
  id: "/_app",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const InviteTokenRoute = InviteTokenImport.update({
  id: "/invite/$token",
  path: "/invite/$token",
  getParentRoute: () => rootRoute,
} as any);

const DevTokensRoute = DevTokensImport.update({
  id: "/dev/tokens",
  path: "/dev/tokens",
  getParentRoute: () => rootRoute,
} as any);

const AppSettingsRoute = AppSettingsImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppRoute,
} as any);

const AppNotFoundRoute = AppNotFoundImport.update({
  id: "/not-found",
  path: "/not-found",
  getParentRoute: () => AppRoute,
} as any);

const AppDashboardRoute = AppDashboardImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AppRoute,
} as any);

const AppCrashTestRoute = AppCrashTestImport.update({
  id: "/crash-test",
  path: "/crash-test",
  getParentRoute: () => AppRoute,
} as any);

const AppTeamsIndexRoute = AppTeamsIndexImport.update({
  id: "/teams/",
  path: "/teams/",
  getParentRoute: () => AppRoute,
} as any);

const AppTeamsNewRoute = AppTeamsNewImport.update({
  id: "/teams/new",
  path: "/teams/new",
  getParentRoute: () => AppRoute,
} as any);

const AppTeamsSlugRoute = AppTeamsSlugImport.update({
  id: "/teams/$slug",
  path: "/teams/$slug",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsNewRoute = AppProjectsNewImport.update({
  id: "/projects/new",
  path: "/projects/new",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsIdRoute = AppProjectsIdImport.update({
  id: "/projects/$id",
  path: "/projects/$id",
  getParentRoute: () => AppRoute,
} as any);

const AppTeamsSlugSettingsRoute = AppTeamsSlugSettingsImport.update({
  id: "/teams/$slug_/settings",
  path: "/teams/$slug/settings",
  getParentRoute: () => AppRoute,
} as any);

const AppTeamsSlugMembersRoute = AppTeamsSlugMembersImport.update({
  id: "/teams/$slug_/members",
  path: "/teams/$slug/members",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsIdTreatmentRoute = AppProjectsIdTreatmentImport.update({
  id: "/projects/$id_/treatment",
  path: "/projects/$id/treatment",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsIdTitlePageRoute = AppProjectsIdTitlePageImport.update({
  id: "/projects/$id_/title-page",
  path: "/projects/$id/title-page",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsIdSynopsisRoute = AppProjectsIdSynopsisImport.update({
  id: "/projects/$id_/synopsis",
  path: "/projects/$id/synopsis",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsIdSoggettoRoute = AppProjectsIdSoggettoImport.update({
  id: "/projects/$id_/soggetto",
  path: "/projects/$id/soggetto",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsIdShootingPlanRoute = AppProjectsIdShootingPlanImport.update({
  id: "/projects/$id_/shooting-plan",
  path: "/projects/$id/shooting-plan",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsIdSettingsRoute = AppProjectsIdSettingsImport.update({
  id: "/projects/$id_/settings",
  path: "/projects/$id/settings",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsIdSessionsRoute = AppProjectsIdSessionsImport.update({
  id: "/projects/$id_/sessions",
  path: "/projects/$id/sessions",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsIdScreenplayRoute = AppProjectsIdScreenplayImport.update({
  id: "/projects/$id_/screenplay",
  path: "/projects/$id/screenplay",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsIdScheduleRoute = AppProjectsIdScheduleImport.update({
  id: "/projects/$id_/schedule",
  path: "/projects/$id/schedule",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsIdOutlineRoute = AppProjectsIdOutlineImport.update({
  id: "/projects/$id_/outline",
  path: "/projects/$id/outline",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsIdOpportunitiesRoute = AppProjectsIdOpportunitiesImport.update(
  {
    id: "/projects/$id_/opportunities",
    path: "/projects/$id/opportunities",
    getParentRoute: () => AppRoute,
  } as any,
);

const AppProjectsIdLoglineRoute = AppProjectsIdLoglineImport.update({
  id: "/projects/$id_/logline",
  path: "/projects/$id/logline",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsIdLocationsRoute = AppProjectsIdLocationsImport.update({
  id: "/projects/$id_/locations",
  path: "/projects/$id/locations",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsIdBudgetRoute = AppProjectsIdBudgetImport.update({
  id: "/projects/$id_/budget",
  path: "/projects/$id/budget",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsIdBreakdownRoute = AppProjectsIdBreakdownImport.update({
  id: "/projects/$id_/breakdown",
  path: "/projects/$id/breakdown",
  getParentRoute: () => AppRoute,
} as any);

const AppProjectsIdSessionsIndexRoute = AppProjectsIdSessionsIndexImport.update(
  {
    id: "/",
    path: "/",
    getParentRoute: () => AppProjectsIdSessionsRoute,
  } as any,
);

const AppProjectsIdScreenplayIndexRoute =
  AppProjectsIdScreenplayIndexImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AppProjectsIdScreenplayRoute,
  } as any);

const AppProjectsIdShootingPlanBlockingEditorRoute =
  AppProjectsIdShootingPlanBlockingEditorImport.update({
    id: "/projects/$id_/shooting-plan_/blocking-editor",
    path: "/projects/$id/shooting-plan/blocking-editor",
    getParentRoute: () => AppRoute,
  } as any);

const AppProjectsIdSessionsNewRoute = AppProjectsIdSessionsNewImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => AppProjectsIdSessionsRoute,
} as any);

const AppProjectsIdSessionsSessionIdRoute =
  AppProjectsIdSessionsSessionIdImport.update({
    id: "/$sessionId",
    path: "/$sessionId",
    getParentRoute: () => AppProjectsIdSessionsRoute,
  } as any);

const AppProjectsIdScreenplayVersionsRoute =
  AppProjectsIdScreenplayVersionsImport.update({
    id: "/versions",
    path: "/versions",
    getParentRoute: () => AppProjectsIdScreenplayRoute,
  } as any);

const AppProjectsIdScreenplayVersionsVIdRoute =
  AppProjectsIdScreenplayVersionsVIdImport.update({
    id: "/$vId",
    path: "/$vId",
    getParentRoute: () => AppProjectsIdScreenplayVersionsRoute,
  } as any);

const AppProjectsIdScreenplayDiffV1V2Route =
  AppProjectsIdScreenplayDiffV1V2Import.update({
    id: "/diff/$v1/$v2",
    path: "/diff/$v1/$v2",
    getParentRoute: () => AppProjectsIdScreenplayRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AppImport;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterImport;
      parentRoute: typeof rootRoute;
    };
    "/_app/crash-test": {
      id: "/_app/crash-test";
      path: "/crash-test";
      fullPath: "/crash-test";
      preLoaderRoute: typeof AppCrashTestImport;
      parentRoute: typeof AppImport;
    };
    "/_app/dashboard": {
      id: "/_app/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AppDashboardImport;
      parentRoute: typeof AppImport;
    };
    "/_app/not-found": {
      id: "/_app/not-found";
      path: "/not-found";
      fullPath: "/not-found";
      preLoaderRoute: typeof AppNotFoundImport;
      parentRoute: typeof AppImport;
    };
    "/_app/settings": {
      id: "/_app/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof AppSettingsImport;
      parentRoute: typeof AppImport;
    };
    "/dev/tokens": {
      id: "/dev/tokens";
      path: "/dev/tokens";
      fullPath: "/dev/tokens";
      preLoaderRoute: typeof DevTokensImport;
      parentRoute: typeof rootRoute;
    };
    "/invite/$token": {
      id: "/invite/$token";
      path: "/invite/$token";
      fullPath: "/invite/$token";
      preLoaderRoute: typeof InviteTokenImport;
      parentRoute: typeof rootRoute;
    };
    "/_app/projects/$id": {
      id: "/_app/projects/$id";
      path: "/projects/$id";
      fullPath: "/projects/$id";
      preLoaderRoute: typeof AppProjectsIdImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/new": {
      id: "/_app/projects/new";
      path: "/projects/new";
      fullPath: "/projects/new";
      preLoaderRoute: typeof AppProjectsNewImport;
      parentRoute: typeof AppImport;
    };
    "/_app/teams/$slug": {
      id: "/_app/teams/$slug";
      path: "/teams/$slug";
      fullPath: "/teams/$slug";
      preLoaderRoute: typeof AppTeamsSlugImport;
      parentRoute: typeof AppImport;
    };
    "/_app/teams/new": {
      id: "/_app/teams/new";
      path: "/teams/new";
      fullPath: "/teams/new";
      preLoaderRoute: typeof AppTeamsNewImport;
      parentRoute: typeof AppImport;
    };
    "/_app/teams/": {
      id: "/_app/teams/";
      path: "/teams";
      fullPath: "/teams";
      preLoaderRoute: typeof AppTeamsIndexImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/breakdown": {
      id: "/_app/projects/$id_/breakdown";
      path: "/projects/$id/breakdown";
      fullPath: "/projects/$id/breakdown";
      preLoaderRoute: typeof AppProjectsIdBreakdownImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/budget": {
      id: "/_app/projects/$id_/budget";
      path: "/projects/$id/budget";
      fullPath: "/projects/$id/budget";
      preLoaderRoute: typeof AppProjectsIdBudgetImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/locations": {
      id: "/_app/projects/$id_/locations";
      path: "/projects/$id/locations";
      fullPath: "/projects/$id/locations";
      preLoaderRoute: typeof AppProjectsIdLocationsImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/logline": {
      id: "/_app/projects/$id_/logline";
      path: "/projects/$id/logline";
      fullPath: "/projects/$id/logline";
      preLoaderRoute: typeof AppProjectsIdLoglineImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/opportunities": {
      id: "/_app/projects/$id_/opportunities";
      path: "/projects/$id/opportunities";
      fullPath: "/projects/$id/opportunities";
      preLoaderRoute: typeof AppProjectsIdOpportunitiesImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/outline": {
      id: "/_app/projects/$id_/outline";
      path: "/projects/$id/outline";
      fullPath: "/projects/$id/outline";
      preLoaderRoute: typeof AppProjectsIdOutlineImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/schedule": {
      id: "/_app/projects/$id_/schedule";
      path: "/projects/$id/schedule";
      fullPath: "/projects/$id/schedule";
      preLoaderRoute: typeof AppProjectsIdScheduleImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/screenplay": {
      id: "/_app/projects/$id_/screenplay";
      path: "/projects/$id/screenplay";
      fullPath: "/projects/$id/screenplay";
      preLoaderRoute: typeof AppProjectsIdScreenplayImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/sessions": {
      id: "/_app/projects/$id_/sessions";
      path: "/projects/$id/sessions";
      fullPath: "/projects/$id/sessions";
      preLoaderRoute: typeof AppProjectsIdSessionsImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/settings": {
      id: "/_app/projects/$id_/settings";
      path: "/projects/$id/settings";
      fullPath: "/projects/$id/settings";
      preLoaderRoute: typeof AppProjectsIdSettingsImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/shooting-plan": {
      id: "/_app/projects/$id_/shooting-plan";
      path: "/projects/$id/shooting-plan";
      fullPath: "/projects/$id/shooting-plan";
      preLoaderRoute: typeof AppProjectsIdShootingPlanImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/soggetto": {
      id: "/_app/projects/$id_/soggetto";
      path: "/projects/$id/soggetto";
      fullPath: "/projects/$id/soggetto";
      preLoaderRoute: typeof AppProjectsIdSoggettoImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/synopsis": {
      id: "/_app/projects/$id_/synopsis";
      path: "/projects/$id/synopsis";
      fullPath: "/projects/$id/synopsis";
      preLoaderRoute: typeof AppProjectsIdSynopsisImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/title-page": {
      id: "/_app/projects/$id_/title-page";
      path: "/projects/$id/title-page";
      fullPath: "/projects/$id/title-page";
      preLoaderRoute: typeof AppProjectsIdTitlePageImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/treatment": {
      id: "/_app/projects/$id_/treatment";
      path: "/projects/$id/treatment";
      fullPath: "/projects/$id/treatment";
      preLoaderRoute: typeof AppProjectsIdTreatmentImport;
      parentRoute: typeof AppImport;
    };
    "/_app/teams/$slug_/members": {
      id: "/_app/teams/$slug_/members";
      path: "/teams/$slug/members";
      fullPath: "/teams/$slug/members";
      preLoaderRoute: typeof AppTeamsSlugMembersImport;
      parentRoute: typeof AppImport;
    };
    "/_app/teams/$slug_/settings": {
      id: "/_app/teams/$slug_/settings";
      path: "/teams/$slug/settings";
      fullPath: "/teams/$slug/settings";
      preLoaderRoute: typeof AppTeamsSlugSettingsImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/screenplay/versions": {
      id: "/_app/projects/$id_/screenplay/versions";
      path: "/versions";
      fullPath: "/projects/$id/screenplay/versions";
      preLoaderRoute: typeof AppProjectsIdScreenplayVersionsImport;
      parentRoute: typeof AppProjectsIdScreenplayImport;
    };
    "/_app/projects/$id_/sessions/$sessionId": {
      id: "/_app/projects/$id_/sessions/$sessionId";
      path: "/$sessionId";
      fullPath: "/projects/$id/sessions/$sessionId";
      preLoaderRoute: typeof AppProjectsIdSessionsSessionIdImport;
      parentRoute: typeof AppProjectsIdSessionsImport;
    };
    "/_app/projects/$id_/sessions/new": {
      id: "/_app/projects/$id_/sessions/new";
      path: "/new";
      fullPath: "/projects/$id/sessions/new";
      preLoaderRoute: typeof AppProjectsIdSessionsNewImport;
      parentRoute: typeof AppProjectsIdSessionsImport;
    };
    "/_app/projects/$id_/shooting-plan_/blocking-editor": {
      id: "/_app/projects/$id_/shooting-plan_/blocking-editor";
      path: "/projects/$id/shooting-plan/blocking-editor";
      fullPath: "/projects/$id/shooting-plan/blocking-editor";
      preLoaderRoute: typeof AppProjectsIdShootingPlanBlockingEditorImport;
      parentRoute: typeof AppImport;
    };
    "/_app/projects/$id_/screenplay/": {
      id: "/_app/projects/$id_/screenplay/";
      path: "/";
      fullPath: "/projects/$id/screenplay/";
      preLoaderRoute: typeof AppProjectsIdScreenplayIndexImport;
      parentRoute: typeof AppProjectsIdScreenplayImport;
    };
    "/_app/projects/$id_/sessions/": {
      id: "/_app/projects/$id_/sessions/";
      path: "/";
      fullPath: "/projects/$id/sessions/";
      preLoaderRoute: typeof AppProjectsIdSessionsIndexImport;
      parentRoute: typeof AppProjectsIdSessionsImport;
    };
    "/_app/projects/$id_/screenplay/versions/$vId": {
      id: "/_app/projects/$id_/screenplay/versions/$vId";
      path: "/$vId";
      fullPath: "/projects/$id/screenplay/versions/$vId";
      preLoaderRoute: typeof AppProjectsIdScreenplayVersionsVIdImport;
      parentRoute: typeof AppProjectsIdScreenplayVersionsImport;
    };
    "/_app/projects/$id_/screenplay/diff/$v1/$v2": {
      id: "/_app/projects/$id_/screenplay/diff/$v1/$v2";
      path: "/diff/$v1/$v2";
      fullPath: "/projects/$id/screenplay/diff/$v1/$v2";
      preLoaderRoute: typeof AppProjectsIdScreenplayDiffV1V2Import;
      parentRoute: typeof AppProjectsIdScreenplayImport;
    };
  }
}

// Create and export the route tree

interface AppProjectsIdScreenplayVersionsRouteChildren {
  AppProjectsIdScreenplayVersionsVIdRoute: typeof AppProjectsIdScreenplayVersionsVIdRoute;
}

const AppProjectsIdScreenplayVersionsRouteChildren: AppProjectsIdScreenplayVersionsRouteChildren =
  {
    AppProjectsIdScreenplayVersionsVIdRoute:
      AppProjectsIdScreenplayVersionsVIdRoute,
  };

const AppProjectsIdScreenplayVersionsRouteWithChildren =
  AppProjectsIdScreenplayVersionsRoute._addFileChildren(
    AppProjectsIdScreenplayVersionsRouteChildren,
  );

interface AppProjectsIdScreenplayRouteChildren {
  AppProjectsIdScreenplayVersionsRoute: typeof AppProjectsIdScreenplayVersionsRouteWithChildren;
  AppProjectsIdScreenplayIndexRoute: typeof AppProjectsIdScreenplayIndexRoute;
  AppProjectsIdScreenplayDiffV1V2Route: typeof AppProjectsIdScreenplayDiffV1V2Route;
}

const AppProjectsIdScreenplayRouteChildren: AppProjectsIdScreenplayRouteChildren =
  {
    AppProjectsIdScreenplayVersionsRoute:
      AppProjectsIdScreenplayVersionsRouteWithChildren,
    AppProjectsIdScreenplayIndexRoute: AppProjectsIdScreenplayIndexRoute,
    AppProjectsIdScreenplayDiffV1V2Route: AppProjectsIdScreenplayDiffV1V2Route,
  };

const AppProjectsIdScreenplayRouteWithChildren =
  AppProjectsIdScreenplayRoute._addFileChildren(
    AppProjectsIdScreenplayRouteChildren,
  );

interface AppProjectsIdSessionsRouteChildren {
  AppProjectsIdSessionsSessionIdRoute: typeof AppProjectsIdSessionsSessionIdRoute;
  AppProjectsIdSessionsNewRoute: typeof AppProjectsIdSessionsNewRoute;
  AppProjectsIdSessionsIndexRoute: typeof AppProjectsIdSessionsIndexRoute;
}

const AppProjectsIdSessionsRouteChildren: AppProjectsIdSessionsRouteChildren = {
  AppProjectsIdSessionsSessionIdRoute: AppProjectsIdSessionsSessionIdRoute,
  AppProjectsIdSessionsNewRoute: AppProjectsIdSessionsNewRoute,
  AppProjectsIdSessionsIndexRoute: AppProjectsIdSessionsIndexRoute,
};

const AppProjectsIdSessionsRouteWithChildren =
  AppProjectsIdSessionsRoute._addFileChildren(
    AppProjectsIdSessionsRouteChildren,
  );

interface AppRouteChildren {
  AppCrashTestRoute: typeof AppCrashTestRoute;
  AppDashboardRoute: typeof AppDashboardRoute;
  AppNotFoundRoute: typeof AppNotFoundRoute;
  AppSettingsRoute: typeof AppSettingsRoute;
  AppProjectsIdRoute: typeof AppProjectsIdRoute;
  AppProjectsNewRoute: typeof AppProjectsNewRoute;
  AppTeamsSlugRoute: typeof AppTeamsSlugRoute;
  AppTeamsNewRoute: typeof AppTeamsNewRoute;
  AppTeamsIndexRoute: typeof AppTeamsIndexRoute;
  AppProjectsIdBreakdownRoute: typeof AppProjectsIdBreakdownRoute;
  AppProjectsIdBudgetRoute: typeof AppProjectsIdBudgetRoute;
  AppProjectsIdLocationsRoute: typeof AppProjectsIdLocationsRoute;
  AppProjectsIdLoglineRoute: typeof AppProjectsIdLoglineRoute;
  AppProjectsIdOpportunitiesRoute: typeof AppProjectsIdOpportunitiesRoute;
  AppProjectsIdOutlineRoute: typeof AppProjectsIdOutlineRoute;
  AppProjectsIdScheduleRoute: typeof AppProjectsIdScheduleRoute;
  AppProjectsIdScreenplayRoute: typeof AppProjectsIdScreenplayRouteWithChildren;
  AppProjectsIdSessionsRoute: typeof AppProjectsIdSessionsRouteWithChildren;
  AppProjectsIdSettingsRoute: typeof AppProjectsIdSettingsRoute;
  AppProjectsIdShootingPlanRoute: typeof AppProjectsIdShootingPlanRoute;
  AppProjectsIdSoggettoRoute: typeof AppProjectsIdSoggettoRoute;
  AppProjectsIdSynopsisRoute: typeof AppProjectsIdSynopsisRoute;
  AppProjectsIdTitlePageRoute: typeof AppProjectsIdTitlePageRoute;
  AppProjectsIdTreatmentRoute: typeof AppProjectsIdTreatmentRoute;
  AppTeamsSlugMembersRoute: typeof AppTeamsSlugMembersRoute;
  AppTeamsSlugSettingsRoute: typeof AppTeamsSlugSettingsRoute;
  AppProjectsIdShootingPlanBlockingEditorRoute: typeof AppProjectsIdShootingPlanBlockingEditorRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppCrashTestRoute: AppCrashTestRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotFoundRoute: AppNotFoundRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppTeamsSlugRoute: AppTeamsSlugRoute,
  AppTeamsNewRoute: AppTeamsNewRoute,
  AppTeamsIndexRoute: AppTeamsIndexRoute,
  AppProjectsIdBreakdownRoute: AppProjectsIdBreakdownRoute,
  AppProjectsIdBudgetRoute: AppProjectsIdBudgetRoute,
  AppProjectsIdLocationsRoute: AppProjectsIdLocationsRoute,
  AppProjectsIdLoglineRoute: AppProjectsIdLoglineRoute,
  AppProjectsIdOpportunitiesRoute: AppProjectsIdOpportunitiesRoute,
  AppProjectsIdOutlineRoute: AppProjectsIdOutlineRoute,
  AppProjectsIdScheduleRoute: AppProjectsIdScheduleRoute,
  AppProjectsIdScreenplayRoute: AppProjectsIdScreenplayRouteWithChildren,
  AppProjectsIdSessionsRoute: AppProjectsIdSessionsRouteWithChildren,
  AppProjectsIdSettingsRoute: AppProjectsIdSettingsRoute,
  AppProjectsIdShootingPlanRoute: AppProjectsIdShootingPlanRoute,
  AppProjectsIdSoggettoRoute: AppProjectsIdSoggettoRoute,
  AppProjectsIdSynopsisRoute: AppProjectsIdSynopsisRoute,
  AppProjectsIdTitlePageRoute: AppProjectsIdTitlePageRoute,
  AppProjectsIdTreatmentRoute: AppProjectsIdTreatmentRoute,
  AppTeamsSlugMembersRoute: AppTeamsSlugMembersRoute,
  AppTeamsSlugSettingsRoute: AppTeamsSlugSettingsRoute,
  AppProjectsIdShootingPlanBlockingEditorRoute:
    AppProjectsIdShootingPlanBlockingEditorRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "": typeof AppRouteWithChildren;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/crash-test": typeof AppCrashTestRoute;
  "/dashboard": typeof AppDashboardRoute;
  "/not-found": typeof AppNotFoundRoute;
  "/settings": typeof AppSettingsRoute;
  "/dev/tokens": typeof DevTokensRoute;
  "/invite/$token": typeof InviteTokenRoute;
  "/projects/$id": typeof AppProjectsIdRoute;
  "/projects/new": typeof AppProjectsNewRoute;
  "/teams/$slug": typeof AppTeamsSlugRoute;
  "/teams/new": typeof AppTeamsNewRoute;
  "/teams": typeof AppTeamsIndexRoute;
  "/projects/$id/breakdown": typeof AppProjectsIdBreakdownRoute;
  "/projects/$id/budget": typeof AppProjectsIdBudgetRoute;
  "/projects/$id/locations": typeof AppProjectsIdLocationsRoute;
  "/projects/$id/logline": typeof AppProjectsIdLoglineRoute;
  "/projects/$id/opportunities": typeof AppProjectsIdOpportunitiesRoute;
  "/projects/$id/outline": typeof AppProjectsIdOutlineRoute;
  "/projects/$id/schedule": typeof AppProjectsIdScheduleRoute;
  "/projects/$id/screenplay": typeof AppProjectsIdScreenplayRouteWithChildren;
  "/projects/$id/sessions": typeof AppProjectsIdSessionsRouteWithChildren;
  "/projects/$id/settings": typeof AppProjectsIdSettingsRoute;
  "/projects/$id/shooting-plan": typeof AppProjectsIdShootingPlanRoute;
  "/projects/$id/soggetto": typeof AppProjectsIdSoggettoRoute;
  "/projects/$id/synopsis": typeof AppProjectsIdSynopsisRoute;
  "/projects/$id/title-page": typeof AppProjectsIdTitlePageRoute;
  "/projects/$id/treatment": typeof AppProjectsIdTreatmentRoute;
  "/teams/$slug/members": typeof AppTeamsSlugMembersRoute;
  "/teams/$slug/settings": typeof AppTeamsSlugSettingsRoute;
  "/projects/$id/screenplay/versions": typeof AppProjectsIdScreenplayVersionsRouteWithChildren;
  "/projects/$id/sessions/$sessionId": typeof AppProjectsIdSessionsSessionIdRoute;
  "/projects/$id/sessions/new": typeof AppProjectsIdSessionsNewRoute;
  "/projects/$id/shooting-plan/blocking-editor": typeof AppProjectsIdShootingPlanBlockingEditorRoute;
  "/projects/$id/screenplay/": typeof AppProjectsIdScreenplayIndexRoute;
  "/projects/$id/sessions/": typeof AppProjectsIdSessionsIndexRoute;
  "/projects/$id/screenplay/versions/$vId": typeof AppProjectsIdScreenplayVersionsVIdRoute;
  "/projects/$id/screenplay/diff/$v1/$v2": typeof AppProjectsIdScreenplayDiffV1V2Route;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "": typeof AppRouteWithChildren;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/crash-test": typeof AppCrashTestRoute;
  "/dashboard": typeof AppDashboardRoute;
  "/not-found": typeof AppNotFoundRoute;
  "/settings": typeof AppSettingsRoute;
  "/dev/tokens": typeof DevTokensRoute;
  "/invite/$token": typeof InviteTokenRoute;
  "/projects/$id": typeof AppProjectsIdRoute;
  "/projects/new": typeof AppProjectsNewRoute;
  "/teams/$slug": typeof AppTeamsSlugRoute;
  "/teams/new": typeof AppTeamsNewRoute;
  "/teams": typeof AppTeamsIndexRoute;
  "/projects/$id/breakdown": typeof AppProjectsIdBreakdownRoute;
  "/projects/$id/budget": typeof AppProjectsIdBudgetRoute;
  "/projects/$id/locations": typeof AppProjectsIdLocationsRoute;
  "/projects/$id/logline": typeof AppProjectsIdLoglineRoute;
  "/projects/$id/opportunities": typeof AppProjectsIdOpportunitiesRoute;
  "/projects/$id/outline": typeof AppProjectsIdOutlineRoute;
  "/projects/$id/schedule": typeof AppProjectsIdScheduleRoute;
  "/projects/$id/settings": typeof AppProjectsIdSettingsRoute;
  "/projects/$id/shooting-plan": typeof AppProjectsIdShootingPlanRoute;
  "/projects/$id/soggetto": typeof AppProjectsIdSoggettoRoute;
  "/projects/$id/synopsis": typeof AppProjectsIdSynopsisRoute;
  "/projects/$id/title-page": typeof AppProjectsIdTitlePageRoute;
  "/projects/$id/treatment": typeof AppProjectsIdTreatmentRoute;
  "/teams/$slug/members": typeof AppTeamsSlugMembersRoute;
  "/teams/$slug/settings": typeof AppTeamsSlugSettingsRoute;
  "/projects/$id/screenplay/versions": typeof AppProjectsIdScreenplayVersionsRouteWithChildren;
  "/projects/$id/sessions/$sessionId": typeof AppProjectsIdSessionsSessionIdRoute;
  "/projects/$id/sessions/new": typeof AppProjectsIdSessionsNewRoute;
  "/projects/$id/shooting-plan/blocking-editor": typeof AppProjectsIdShootingPlanBlockingEditorRoute;
  "/projects/$id/screenplay": typeof AppProjectsIdScreenplayIndexRoute;
  "/projects/$id/sessions": typeof AppProjectsIdSessionsIndexRoute;
  "/projects/$id/screenplay/versions/$vId": typeof AppProjectsIdScreenplayVersionsVIdRoute;
  "/projects/$id/screenplay/diff/$v1/$v2": typeof AppProjectsIdScreenplayDiffV1V2Route;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/_app": typeof AppRouteWithChildren;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/_app/crash-test": typeof AppCrashTestRoute;
  "/_app/dashboard": typeof AppDashboardRoute;
  "/_app/not-found": typeof AppNotFoundRoute;
  "/_app/settings": typeof AppSettingsRoute;
  "/dev/tokens": typeof DevTokensRoute;
  "/invite/$token": typeof InviteTokenRoute;
  "/_app/projects/$id": typeof AppProjectsIdRoute;
  "/_app/projects/new": typeof AppProjectsNewRoute;
  "/_app/teams/$slug": typeof AppTeamsSlugRoute;
  "/_app/teams/new": typeof AppTeamsNewRoute;
  "/_app/teams/": typeof AppTeamsIndexRoute;
  "/_app/projects/$id_/breakdown": typeof AppProjectsIdBreakdownRoute;
  "/_app/projects/$id_/budget": typeof AppProjectsIdBudgetRoute;
  "/_app/projects/$id_/locations": typeof AppProjectsIdLocationsRoute;
  "/_app/projects/$id_/logline": typeof AppProjectsIdLoglineRoute;
  "/_app/projects/$id_/opportunities": typeof AppProjectsIdOpportunitiesRoute;
  "/_app/projects/$id_/outline": typeof AppProjectsIdOutlineRoute;
  "/_app/projects/$id_/schedule": typeof AppProjectsIdScheduleRoute;
  "/_app/projects/$id_/screenplay": typeof AppProjectsIdScreenplayRouteWithChildren;
  "/_app/projects/$id_/sessions": typeof AppProjectsIdSessionsRouteWithChildren;
  "/_app/projects/$id_/settings": typeof AppProjectsIdSettingsRoute;
  "/_app/projects/$id_/shooting-plan": typeof AppProjectsIdShootingPlanRoute;
  "/_app/projects/$id_/soggetto": typeof AppProjectsIdSoggettoRoute;
  "/_app/projects/$id_/synopsis": typeof AppProjectsIdSynopsisRoute;
  "/_app/projects/$id_/title-page": typeof AppProjectsIdTitlePageRoute;
  "/_app/projects/$id_/treatment": typeof AppProjectsIdTreatmentRoute;
  "/_app/teams/$slug_/members": typeof AppTeamsSlugMembersRoute;
  "/_app/teams/$slug_/settings": typeof AppTeamsSlugSettingsRoute;
  "/_app/projects/$id_/screenplay/versions": typeof AppProjectsIdScreenplayVersionsRouteWithChildren;
  "/_app/projects/$id_/sessions/$sessionId": typeof AppProjectsIdSessionsSessionIdRoute;
  "/_app/projects/$id_/sessions/new": typeof AppProjectsIdSessionsNewRoute;
  "/_app/projects/$id_/shooting-plan_/blocking-editor": typeof AppProjectsIdShootingPlanBlockingEditorRoute;
  "/_app/projects/$id_/screenplay/": typeof AppProjectsIdScreenplayIndexRoute;
  "/_app/projects/$id_/sessions/": typeof AppProjectsIdSessionsIndexRoute;
  "/_app/projects/$id_/screenplay/versions/$vId": typeof AppProjectsIdScreenplayVersionsVIdRoute;
  "/_app/projects/$id_/screenplay/diff/$v1/$v2": typeof AppProjectsIdScreenplayDiffV1V2Route;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | ""
    | "/login"
    | "/register"
    | "/crash-test"
    | "/dashboard"
    | "/not-found"
    | "/settings"
    | "/dev/tokens"
    | "/invite/$token"
    | "/projects/$id"
    | "/projects/new"
    | "/teams/$slug"
    | "/teams/new"
    | "/teams"
    | "/projects/$id/breakdown"
    | "/projects/$id/budget"
    | "/projects/$id/locations"
    | "/projects/$id/logline"
    | "/projects/$id/opportunities"
    | "/projects/$id/outline"
    | "/projects/$id/schedule"
    | "/projects/$id/screenplay"
    | "/projects/$id/sessions"
    | "/projects/$id/settings"
    | "/projects/$id/shooting-plan"
    | "/projects/$id/soggetto"
    | "/projects/$id/synopsis"
    | "/projects/$id/title-page"
    | "/projects/$id/treatment"
    | "/teams/$slug/members"
    | "/teams/$slug/settings"
    | "/projects/$id/screenplay/versions"
    | "/projects/$id/sessions/$sessionId"
    | "/projects/$id/sessions/new"
    | "/projects/$id/shooting-plan/blocking-editor"
    | "/projects/$id/screenplay/"
    | "/projects/$id/sessions/"
    | "/projects/$id/screenplay/versions/$vId"
    | "/projects/$id/screenplay/diff/$v1/$v2";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | ""
    | "/login"
    | "/register"
    | "/crash-test"
    | "/dashboard"
    | "/not-found"
    | "/settings"
    | "/dev/tokens"
    | "/invite/$token"
    | "/projects/$id"
    | "/projects/new"
    | "/teams/$slug"
    | "/teams/new"
    | "/teams"
    | "/projects/$id/breakdown"
    | "/projects/$id/budget"
    | "/projects/$id/locations"
    | "/projects/$id/logline"
    | "/projects/$id/opportunities"
    | "/projects/$id/outline"
    | "/projects/$id/schedule"
    | "/projects/$id/settings"
    | "/projects/$id/shooting-plan"
    | "/projects/$id/soggetto"
    | "/projects/$id/synopsis"
    | "/projects/$id/title-page"
    | "/projects/$id/treatment"
    | "/teams/$slug/members"
    | "/teams/$slug/settings"
    | "/projects/$id/screenplay/versions"
    | "/projects/$id/sessions/$sessionId"
    | "/projects/$id/sessions/new"
    | "/projects/$id/shooting-plan/blocking-editor"
    | "/projects/$id/screenplay"
    | "/projects/$id/sessions"
    | "/projects/$id/screenplay/versions/$vId"
    | "/projects/$id/screenplay/diff/$v1/$v2";
  id:
    | "__root__"
    | "/"
    | "/_app"
    | "/login"
    | "/register"
    | "/_app/crash-test"
    | "/_app/dashboard"
    | "/_app/not-found"
    | "/_app/settings"
    | "/dev/tokens"
    | "/invite/$token"
    | "/_app/projects/$id"
    | "/_app/projects/new"
    | "/_app/teams/$slug"
    | "/_app/teams/new"
    | "/_app/teams/"
    | "/_app/projects/$id_/breakdown"
    | "/_app/projects/$id_/budget"
    | "/_app/projects/$id_/locations"
    | "/_app/projects/$id_/logline"
    | "/_app/projects/$id_/opportunities"
    | "/_app/projects/$id_/outline"
    | "/_app/projects/$id_/schedule"
    | "/_app/projects/$id_/screenplay"
    | "/_app/projects/$id_/sessions"
    | "/_app/projects/$id_/settings"
    | "/_app/projects/$id_/shooting-plan"
    | "/_app/projects/$id_/soggetto"
    | "/_app/projects/$id_/synopsis"
    | "/_app/projects/$id_/title-page"
    | "/_app/projects/$id_/treatment"
    | "/_app/teams/$slug_/members"
    | "/_app/teams/$slug_/settings"
    | "/_app/projects/$id_/screenplay/versions"
    | "/_app/projects/$id_/sessions/$sessionId"
    | "/_app/projects/$id_/sessions/new"
    | "/_app/projects/$id_/shooting-plan_/blocking-editor"
    | "/_app/projects/$id_/screenplay/"
    | "/_app/projects/$id_/sessions/"
    | "/_app/projects/$id_/screenplay/versions/$vId"
    | "/_app/projects/$id_/screenplay/diff/$v1/$v2";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRoute: typeof AppRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
  DevTokensRoute: typeof DevTokensRoute;
  InviteTokenRoute: typeof InviteTokenRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DevTokensRoute: DevTokensRoute,
  InviteTokenRoute: InviteTokenRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/login",
        "/register",
        "/dev/tokens",
        "/invite/$token"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/crash-test",
        "/_app/dashboard",
        "/_app/not-found",
        "/_app/settings",
        "/_app/projects/$id",
        "/_app/projects/new",
        "/_app/teams/$slug",
        "/_app/teams/new",
        "/_app/teams/",
        "/_app/projects/$id_/breakdown",
        "/_app/projects/$id_/budget",
        "/_app/projects/$id_/locations",
        "/_app/projects/$id_/logline",
        "/_app/projects/$id_/opportunities",
        "/_app/projects/$id_/outline",
        "/_app/projects/$id_/schedule",
        "/_app/projects/$id_/screenplay",
        "/_app/projects/$id_/sessions",
        "/_app/projects/$id_/settings",
        "/_app/projects/$id_/shooting-plan",
        "/_app/projects/$id_/soggetto",
        "/_app/projects/$id_/synopsis",
        "/_app/projects/$id_/title-page",
        "/_app/projects/$id_/treatment",
        "/_app/teams/$slug_/members",
        "/_app/teams/$slug_/settings",
        "/_app/projects/$id_/shooting-plan_/blocking-editor"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/_app/crash-test": {
      "filePath": "_app.crash-test.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard": {
      "filePath": "_app.dashboard.tsx",
      "parent": "/_app"
    },
    "/_app/not-found": {
      "filePath": "_app.not-found.tsx",
      "parent": "/_app"
    },
    "/_app/settings": {
      "filePath": "_app.settings.tsx",
      "parent": "/_app"
    },
    "/dev/tokens": {
      "filePath": "dev/tokens.tsx"
    },
    "/invite/$token": {
      "filePath": "invite.$token.tsx"
    },
    "/_app/projects/$id": {
      "filePath": "_app.projects.$id.tsx",
      "parent": "/_app"
    },
    "/_app/projects/new": {
      "filePath": "_app.projects.new.tsx",
      "parent": "/_app"
    },
    "/_app/teams/$slug": {
      "filePath": "_app.teams.$slug.tsx",
      "parent": "/_app"
    },
    "/_app/teams/new": {
      "filePath": "_app.teams.new.tsx",
      "parent": "/_app"
    },
    "/_app/teams/": {
      "filePath": "_app.teams.index.tsx",
      "parent": "/_app"
    },
    "/_app/projects/$id_/breakdown": {
      "filePath": "_app.projects.$id_.breakdown.tsx",
      "parent": "/_app"
    },
    "/_app/projects/$id_/budget": {
      "filePath": "_app.projects.$id_.budget.tsx",
      "parent": "/_app"
    },
    "/_app/projects/$id_/locations": {
      "filePath": "_app.projects.$id_.locations.tsx",
      "parent": "/_app"
    },
    "/_app/projects/$id_/logline": {
      "filePath": "_app.projects.$id_.logline.tsx",
      "parent": "/_app"
    },
    "/_app/projects/$id_/opportunities": {
      "filePath": "_app.projects.$id_.opportunities.tsx",
      "parent": "/_app"
    },
    "/_app/projects/$id_/outline": {
      "filePath": "_app.projects.$id_.outline.tsx",
      "parent": "/_app"
    },
    "/_app/projects/$id_/schedule": {
      "filePath": "_app.projects.$id_.schedule.tsx",
      "parent": "/_app"
    },
    "/_app/projects/$id_/screenplay": {
      "filePath": "_app.projects.$id_.screenplay.tsx",
      "parent": "/_app",
      "children": [
        "/_app/projects/$id_/screenplay/versions",
        "/_app/projects/$id_/screenplay/",
        "/_app/projects/$id_/screenplay/diff/$v1/$v2"
      ]
    },
    "/_app/projects/$id_/sessions": {
      "filePath": "_app.projects.$id_.sessions.tsx",
      "parent": "/_app",
      "children": [
        "/_app/projects/$id_/sessions/$sessionId",
        "/_app/projects/$id_/sessions/new",
        "/_app/projects/$id_/sessions/"
      ]
    },
    "/_app/projects/$id_/settings": {
      "filePath": "_app.projects.$id_.settings.tsx",
      "parent": "/_app"
    },
    "/_app/projects/$id_/shooting-plan": {
      "filePath": "_app.projects.$id_.shooting-plan.tsx",
      "parent": "/_app"
    },
    "/_app/projects/$id_/soggetto": {
      "filePath": "_app.projects.$id_.soggetto.tsx",
      "parent": "/_app"
    },
    "/_app/projects/$id_/synopsis": {
      "filePath": "_app.projects.$id_.synopsis.tsx",
      "parent": "/_app"
    },
    "/_app/projects/$id_/title-page": {
      "filePath": "_app.projects.$id_.title-page.tsx",
      "parent": "/_app"
    },
    "/_app/projects/$id_/treatment": {
      "filePath": "_app.projects.$id_.treatment.tsx",
      "parent": "/_app"
    },
    "/_app/teams/$slug_/members": {
      "filePath": "_app.teams.$slug_.members.tsx",
      "parent": "/_app"
    },
    "/_app/teams/$slug_/settings": {
      "filePath": "_app.teams.$slug_.settings.tsx",
      "parent": "/_app"
    },
    "/_app/projects/$id_/screenplay/versions": {
      "filePath": "_app.projects.$id_.screenplay.versions.tsx",
      "parent": "/_app/projects/$id_/screenplay",
      "children": [
        "/_app/projects/$id_/screenplay/versions/$vId"
      ]
    },
    "/_app/projects/$id_/sessions/$sessionId": {
      "filePath": "_app.projects.$id_.sessions.$sessionId.tsx",
      "parent": "/_app/projects/$id_/sessions"
    },
    "/_app/projects/$id_/sessions/new": {
      "filePath": "_app.projects.$id_.sessions.new.tsx",
      "parent": "/_app/projects/$id_/sessions"
    },
    "/_app/projects/$id_/shooting-plan_/blocking-editor": {
      "filePath": "_app.projects.$id_.shooting-plan_.blocking-editor.tsx",
      "parent": "/_app"
    },
    "/_app/projects/$id_/screenplay/": {
      "filePath": "_app.projects.$id_.screenplay.index.tsx",
      "parent": "/_app/projects/$id_/screenplay"
    },
    "/_app/projects/$id_/sessions/": {
      "filePath": "_app.projects.$id_.sessions.index.tsx",
      "parent": "/_app/projects/$id_/sessions"
    },
    "/_app/projects/$id_/screenplay/versions/$vId": {
      "filePath": "_app.projects.$id_.screenplay.versions.$vId.tsx",
      "parent": "/_app/projects/$id_/screenplay/versions"
    },
    "/_app/projects/$id_/screenplay/diff/$v1/$v2": {
      "filePath": "_app.projects.$id_.screenplay.diff.$v1.$v2.tsx",
      "parent": "/_app/projects/$id_/screenplay"
    }
  }
}
ROUTE_MANIFEST_END */
