/**
 * Vernissage scaffold — turns a *.story.json into a Playwright E2E spec that
 * runs against the mocked Cesare loop (MOCK_AI=true). The emitted file is a
 * starting point; the human (or downstream agent) still has to:
 *
 *   1. Open `apps/web/app/features/predictions/_mocks/cesare-tool-loop.mock.ts`
 *   2. Paste the `MockScenario` skeleton emitted at the top of the spec
 *   3. Fill in the tool name(s) + input shape — the scaffold cannot infer them
 *
 * The scaffold is intentionally read-only on everything except the spec it
 * writes. It never edits the mock file, never touches the walk artifacts, and
 * refuses to overwrite an existing spec unless --force is passed.
 *
 * Run example:
 *   pnpm vernissage:scaffold -- --story=vernissage/_stories/foo.story.json
 */
import { readdir, rename, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  escapeRegex,
  loadJson,
  parseArgs,
  validateStory,
  type Step,
  type Story,
} from "./vernissage/lib.ts";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, "..");
const TESTS_DIR = path.join(REPO_ROOT, "tests");

const ALLOWED_FLAGS = ["story", "out", "tag", "force", "help"] as const;

const HELP = `vernissage-scaffold — generate a Playwright spec from a vernissage story

Usage:
  pnpm vernissage:scaffold -- --story=<path> [--out=<path>] [--tag=OHW-XXX] [--force]

Flags:
  --story=<path>     Path to a *.story.json file (required).
  --out=<path>       Target spec file (default: tests/cesare-agentic-<story.id>.spec.ts).
  --tag=OHW-XXX      Override the auto-picked OHW tag.
  --force            Overwrite an existing spec at --out.
  --help             Show this message.
`;

const CESARE_PROMPT_PLACEHOLDER = `[placeholder="Chiedi a Cesare…"]`;

async function fileExists(p: string): Promise<boolean> {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}

async function walkSpecFiles(dir: string): Promise<string[]> {
  const out: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...(await walkSpecFiles(full)));
    } else if (entry.isFile() && entry.name.endsWith(".spec.ts")) {
      out.push(full);
    }
  }
  return out;
}

async function nextOhwTag(): Promise<string> {
  const files = await walkSpecFiles(TESTS_DIR);
  let maxN = 0;
  const pattern = /\[OHW-(\d+)\]/g;
  for (const file of files) {
    const content = await (
      await import("node:fs/promises")
    ).readFile(file, "utf-8");
    for (const match of content.matchAll(pattern)) {
      const n = parseInt(match[1] ?? "0", 10);
      if (Number.isFinite(n) && n > maxN) maxN = n;
    }
  }
  const next = maxN + 1;
  return `OHW-${String(next).padStart(3, "0")}`;
}

function firstUserPrompt(story: Story): string | null {
  // The user's prompt to Cesare is the first non-empty `type` step targeting
  // the Cesare textarea. Everything else (search filters, scene titles) is
  // not a Cesare-loop trigger.
  for (const step of story.steps) {
    if (
      step.kind === "type" &&
      step.ref.includes(`Chiedi a Cesare`) &&
      step.text.trim().length > 0
    ) {
      return step.text;
    }
  }
  return null;
}

function emitMockScenarioComment(story: Story): string {
  const prompt = firstUserPrompt(story);
  const matchLiteral = prompt
    ? `/${escapeRegex(prompt)}/i`
    : `/TODO-replace-me/i`;
  return [
    `/**`,
    ` * AUTO-GENERATED by vernissage-scaffold from`,
    ` *   vernissage/_stories/${story.id}.story.json`,
    ` *`,
    ` * Do NOT hand-edit. Re-run the scaffold and amend the story file instead.`,
    ` *`,
    ` * MockScenario skeleton — paste into`,
    ` *   apps/web/app/features/predictions/_mocks/cesare-tool-loop.mock.ts`,
    ` * then fill in the TODOs.`,
    ` *`,
    ` *   {`,
    ` *     match: ${matchLiteral},`,
    ` *     turns: [`,
    ` *       {`,
    ` *         stop_reason: "tool_use",`,
    ` *         tool_uses: [`,
    ` *           {`,
    ` *             // TODO: real tool name from the agentic spec`,
    ` *             name: "TODO_TOOL_NAME",`,
    ` *             input: { /* TODO: real input shape, supports {{PLACEHOLDERS}} */ },`,
    ` *           },`,
    ` *         ],`,
    ` *       },`,
    ` *       {`,
    ` *         stop_reason: "end_turn",`,
    ` *         text: "✦ TODO: final assistant message that triggers the UI toast.",`,
    ` *       },`,
    ` *     ],`,
    ` *   }`,
    ` */`,
  ].join("\n");
}

interface CollapsedPattern {
  startIdx: number;
  endIdx: number;
  prompt: string;
}

/**
 * Detect a `type` step on the Cesare textarea followed by either a
 * `press Enter` or a click on the send button — collapse it into a single
 * sendCesareMessage + waitForCesareReply pair when emitting the spec body.
 */
function findCesareSendPatterns(steps: Step[]): CollapsedPattern[] {
  const out: CollapsedPattern[] = [];
  for (let i = 0; i < steps.length - 1; i++) {
    const a = steps[i];
    const b = steps[i + 1];
    if (!a || !b) continue;
    if (a.kind !== "type") continue;
    if (!a.ref.includes("Chiedi a Cesare")) continue;
    const submits =
      (b.kind === "press" && b.key === "Enter") ||
      (b.kind === "click" && /invia/i.test(b.ref));
    if (!submits) continue;
    out.push({ startIdx: i, endIdx: i + 1, prompt: a.text });
  }
  return out;
}

function quoteJs(value: string): string {
  return JSON.stringify(value);
}

function isLocatorRef(ref: string): boolean {
  return /^getBy[A-Z]/.test(ref);
}

function refToLocator(pageVar: string, ref: string): string {
  if (isLocatorRef(ref)) return `${pageVar}.${ref}`;
  return `${pageVar}.locator(${quoteJs(ref)})`;
}

function emitStep(
  step: Step,
  pageVar: string,
  collapsedAt: Set<number>,
  idx: number,
): string[] {
  if (collapsedAt.has(idx)) return [];
  switch (step.kind) {
    case "wait_for": {
      const timeout = step.timeout_ms ?? 10_000;
      return [
        `  await expect(${pageVar}.locator(${quoteJs(step.selector)})).toBeVisible({ timeout: ${timeout} });`,
      ];
    }
    case "click":
      return [`  await ${refToLocator(pageVar, step.ref)}.click();`];
    case "type":
      return [
        `  await ${refToLocator(pageVar, step.ref)}.fill(${quoteJs(step.text)});`,
      ];
    case "press":
      return [`  await ${pageVar}.keyboard.press(${quoteJs(step.key)});`];
    case "screenshot":
      // Screenshot steps are intentionally a no-op in the emitted spec —
      // they're walk-only artifacts, not part of the assertion path.
      return [`  // screenshot step (walk-only): ${step.filename}`];
    case "expect_dom": {
      const loc = `${pageVar}.locator(${quoteJs(step.selector)})`;
      return step.exists
        ? [`  await expect(${loc}).toBeVisible({ timeout: 10_000 });`]
        : [`  await expect(${loc}).toHaveCount(0);`];
    }
    case "expect_text":
      return [
        `  await expect(${pageVar}.locator(${quoteJs(step.selector)})).toContainText(${quoteJs(step.text)});`,
      ];
    case "eval": {
      const body = quoteJs(step.expr);
      if (step.expect === undefined) {
        return [`  await ${pageVar}.evaluate(${body});`];
      }
      return [
        `  expect(await ${pageVar}.evaluate(${body})).toEqual(${JSON.stringify(step.expect)});`,
      ];
    }
  }
}

function buildSpec(story: Story, tag: string): string {
  const lines: string[] = [];
  const pageVar = "authenticatedPage";

  lines.push(`import { test, expect } from "./fixtures";`);
  lines.push(`import {`);
  lines.push(`  openCesareSheet,`);
  lines.push(`  sendCesareMessage,`);
  lines.push(`  waitForCesareReply,`);
  if (story.mockContext) lines.push(`  setMockContext,`);
  lines.push(`} from "./helpers/cesare";`);
  lines.push(``);
  lines.push(emitMockScenarioComment(story));
  lines.push(``);
  lines.push(`test.describe(${quoteJs(story.title)}, () => {`);
  lines.push(
    `  test(${quoteJs(`[${tag}] ${story.title}`)}, async ({ ${pageVar} }) => {`,
  );

  if (story.mockContext) {
    const ctxLiteral = JSON.stringify(story.mockContext, null, 2)
      .split("\n")
      .map((l, i) => (i === 0 ? l : `    ${l}`))
      .join("\n");
    lines.push(`    await setMockContext(${pageVar}, ${ctxLiteral});`);
  }

  lines.push(`    await ${pageVar}.goto(${quoteJs(story.url)});`);

  const collapsed = findCesareSendPatterns(story.steps);
  const collapsedAt = new Set<number>();
  for (const c of collapsed) {
    collapsedAt.add(c.startIdx);
    collapsedAt.add(c.endIdx);
  }

  // Track whether we've opened the Cesare sheet so we can inject openCesareSheet
  // automatically before the first sendCesareMessage call.
  let cesareSheetOpened = false;

  for (let i = 0; i < story.steps.length; i++) {
    const step = story.steps[i];
    if (!step) continue;
    const matchedCollapse = collapsed.find((c) => c.startIdx === i);
    if (matchedCollapse) {
      if (!cesareSheetOpened) {
        lines.push(`    await openCesareSheet(${pageVar});`);
        cesareSheetOpened = true;
      }
      lines.push(
        `    await sendCesareMessage(${pageVar}, ${quoteJs(matchedCollapse.prompt)});`,
      );
      lines.push(`    const reply = await waitForCesareReply(${pageVar});`);
      lines.push(`    expect(reply.length).toBeGreaterThan(0);`);
      continue;
    }
    if (collapsedAt.has(i)) continue;
    // Detect a click on the Cesare trigger and call openCesareSheet helper.
    if (
      step.kind === "click" &&
      /Cesare/.test(step.ref) &&
      !cesareSheetOpened
    ) {
      lines.push(`    await openCesareSheet(${pageVar});`);
      cesareSheetOpened = true;
      continue;
    }
    const emitted = emitStep(step, pageVar, collapsedAt, i);
    for (const e of emitted) {
      // emitStep already prefixes with two spaces; we want four inside the test body.
      lines.push(`  ${e}`);
    }
  }

  lines.push(`  });`);
  lines.push(`});`);
  lines.push(``);
  return lines.join("\n");
}

async function main(): Promise<void> {
  let args: Record<string, string | true>;
  try {
    args = parseArgs(
      process.argv.slice(2),
      ALLOWED_FLAGS as ReadonlyArray<string>,
    );
  } catch (e) {
    process.stderr.write(`${(e as Error).message}\n\n${HELP}`);
    process.exit(2);
  }
  if (args["help"]) {
    process.stdout.write(HELP);
    process.exit(0);
  }

  const storyPath = args["story"];
  if (typeof storyPath !== "string") {
    process.stderr.write(`Missing required --story=<path>\n\n${HELP}`);
    process.exit(2);
  }

  let raw: unknown;
  try {
    raw = await loadJson(path.resolve(REPO_ROOT, storyPath));
  } catch (e) {
    process.stderr.write(
      `Failed to load story at ${storyPath}: ${(e as Error).message}\n`,
    );
    process.exit(2);
  }

  const validation = validateStory(raw);
  if (!validation.ok) {
    process.stderr.write(
      `Invalid story:\n  - ${validation.errors.join("\n  - ")}\n`,
    );
    process.exit(2);
  }
  const story = validation.story;

  const tag =
    typeof args["tag"] === "string" ? args["tag"] : await nextOhwTag();
  const outPath =
    typeof args["out"] === "string"
      ? path.resolve(REPO_ROOT, args["out"])
      : path.resolve(TESTS_DIR, `cesare-agentic-${story.id}.spec.ts`);

  if ((await fileExists(outPath)) && args["force"] !== true) {
    process.stderr.write(
      `Refusing to overwrite ${path.relative(REPO_ROOT, outPath)} (pass --force to allow).\n`,
    );
    process.exit(4);
  }

  // Acknowledge the Cesare prompt placeholder lives in this scope; the value
  // is exported for grep-ability so future refactors can find both sides.
  void CESARE_PROMPT_PLACEHOLDER;

  const spec = buildSpec(story, tag);
  const tmpPath = `${outPath}.tmp`;
  await writeFile(tmpPath, spec);
  await rename(tmpPath, outPath);

  process.stdout.write(
    `Wrote ${path.relative(REPO_ROOT, outPath)}. Tag: [${tag}].\n` +
      `Next: paste the MockScenario block from the spec header into ` +
      `apps/web/app/features/predictions/_mocks/cesare-tool-loop.mock.ts and replace TODOs.\n`,
  );
}

main().catch((e: unknown) => {
  process.stderr.write(
    `vernissage-scaffold crashed: ${(e as Error).message}\n`,
  );
  process.exit(99);
});
